name: aibootcamp
channels:
  - conda-forge

dependencies:
  - python=3.7.5
  - numpy=1.18.1
  - pandas=1.0.1
  - gensim=3.8.1
  - spacy=2.2.3
  - scikit-learn=0.22.1
  - nltk=3.4.5
  - matplotlib=3.1.3
  - pytorch=1.3.1
  - tensorboard=2.1.0
  - jupyter=1.0.0
  - ipykernel=5.1.4
  - pip=20.0.2

  - pip:
    - docx2txt==0.8
    - transformers==2.5.1
    - pylint>=2.3
    - pep8>=1.7
    - autopep8>=1.4
